language:
  - clojure
  - node_js
lein: lein2
node_js:
  "0.10"
install:
  - npm install
before_script:
  - lein2 classpath
  - lein2 cljsbuild once
script:
  - npm test && wget http://ssl.solsort.com/travis-ok
  - lein bikeshed -m 1000
